pragma Singleton

import Quickshell
import Quickshell.Io
import QtQuick

// The shell palette, read at runtime from the JSON matugen writes.
//
// This file used to be generated by matugen directly. Writing a .qml file made
// Quickshell reload the whole configuration, so every object was rebuilt and
// the colours snapped over instantly with no way to animate them. The palette
// now lands in ~/.cache/matugen/colors.json, outside the config directory,
// and this singleton watches that file. Nothing is rebuilt, so the public
// properties below can simply ease into their new values.
//
// Every consumer keeps using Colors.bg, Colors.accent and so on; the
// transition is invisible from the outside.
Singleton {
    id: root

    // How long the palette takes to cross over. Long enough to read as a
    // change of light rather than a glitch, short enough not to feel broken.
    readonly property int morph: 650

    // Values straight off disk. The defaults are only ever seen if the cache
    // is missing, which happens exactly once on a fresh machine before the
    // first matugen run.
    property color srcBg:           "#18120e"
    property color srcBgAlt:        "#51443a"
    property color srcFg:           "#ece0d9"
    property color srcFgDim:        "#d6c3b5"
    property color srcOutline:      "#9f8e81"
    property color srcOutlineFaint: "#51443a"
    property color srcAccent:       "#feb879"
    property color srcAccentAlt:    "#c8cc7a"
    property color srcAccentText:   "#4b2700"
    property color srcBad:          "#ffb4ab"

    FileView {
        id: file
        path: Quickshell.env("HOME") + "/.cache/matugen/colors.json"
        watchChanges: true

        onFileChanged: reload()
        onLoaded: {
            let p;
            try {
                p = JSON.parse(file.text());
            } catch (e) {
                // A half-written file during a matugen run parses as garbage.
                // Keeping the previous palette is better than flashing to the
                // defaults and back.
                return;
            }

            if (p.bg)           root.srcBg = p.bg;
            if (p.bgAlt)        root.srcBgAlt = p.bgAlt;
            if (p.fg)           root.srcFg = p.fg;
            if (p.fgDim)        root.srcFgDim = p.fgDim;
            if (p.outline)      root.srcOutline = p.outline;
            if (p.outlineFaint) root.srcOutlineFaint = p.outlineFaint;
            if (p.accent)       root.srcAccent = p.accent;
            if (p.accentAlt)    root.srcAccentAlt = p.accentAlt;
            if (p.accentText)   root.srcAccentText = p.accentText;
            if (p.bad)          root.srcBad = p.bad;
        }
    }

    // --- public palette ---------------------------------------------------
    //
    // Each of these follows its source value through a ColorAnimation, so a
    // wallpaper change washes across the whole shell instead of cutting.

    property color bg: srcBg
    Behavior on bg { ColorAnimation { duration: root.morph; easing.type: Easing.InOutCubic } }

    property color bgAlt: srcBgAlt
    Behavior on bgAlt { ColorAnimation { duration: root.morph; easing.type: Easing.InOutCubic } }

    property color fg: srcFg
    Behavior on fg { ColorAnimation { duration: root.morph; easing.type: Easing.InOutCubic } }

    property color fgDim: srcFgDim
    Behavior on fgDim { ColorAnimation { duration: root.morph; easing.type: Easing.InOutCubic } }

    property color outline: srcOutline
    Behavior on outline { ColorAnimation { duration: root.morph; easing.type: Easing.InOutCubic } }

    property color outlineFaint: srcOutlineFaint
    Behavior on outlineFaint { ColorAnimation { duration: root.morph; easing.type: Easing.InOutCubic } }

    // The accents lag slightly behind the surfaces. Moving everything on the
    // same clock looks like a filter being applied; a small offset reads as
    // the scheme rebuilding itself.
    property color accent: srcAccent
    Behavior on accent {
        SequentialAnimation {
            PauseAnimation { duration: 90 }
            ColorAnimation { duration: root.morph; easing.type: Easing.InOutCubic }
        }
    }

    property color accentAlt: srcAccentAlt
    Behavior on accentAlt {
        SequentialAnimation {
            PauseAnimation { duration: 140 }
            ColorAnimation { duration: root.morph; easing.type: Easing.InOutCubic }
        }
    }

    property color accentText: srcAccentText
    Behavior on accentText { ColorAnimation { duration: root.morph; easing.type: Easing.InOutCubic } }

    property color bad: srcBad
    Behavior on bad { ColorAnimation { duration: root.morph; easing.type: Easing.InOutCubic } }

    // Status colours keep their meaning through hue - red, amber, green - but
    // borrow saturation and lightness from the scheme's own error colour, so
    // they sit in the same tonal range as everything else instead of looking
    // pasted in from another palette. They follow `bad`, so they cross over
    // with it for free.
    readonly property real statusSat:
        Math.max(0.45, Math.min(0.85, bad.hslSaturation))
    readonly property real statusLight:
        Math.max(0.55, Math.min(0.80, bad.hslLightness))

    readonly property color warn: Qt.hsla(0.11, statusSat, statusLight, 1)
    readonly property color good: Qt.hsla(0.36, statusSat, statusLight, 1)
}
