import Quickshell
import Quickshell.Hyprland
import Quickshell.Io
import Quickshell.Services.Notifications
import QtQuick
import Quickshell.Wayland

Scope {
    id: root

    // Sounds are generated by ~/.config/hypr/scripts/gen-notify-sounds.py.
    readonly property string soundDir:
        Quickshell.env("HOME") + "/.local/share/sounds/f/"

    // Rate limit: a burst of notifications should not turn into a burst of
    // overlapping blips.
    property double lastSoundAt: 0

    Process { id: player }

    function play(file) {
        const now = Date.now();
        if (now - root.lastSoundAt < 350)
            return;
        root.lastSoundAt = now;

        player.running = false;
        player.command = ["pw-play", "--volume=0.5", root.soundDir + file];
        player.running = true;
    }

    NotificationServer {
        id: server
        keepOnReload: false
        actionsSupported: true
        bodySupported: true
        bodyMarkupSupported: true
        imageSupported: true

        onNotification: function (n) {
            n.tracked = true;

            // Apps that push transient progress updates (volume, download
            // percentages) would otherwise chirp on every step.
            if (n.transient)
                return;

            root.play(n.urgency === NotificationUrgency.Critical
                      ? "critical.wav" : "notify.wav");
        }
    }

    PanelWindow {
        WlrLayershell.namespace: "qs-notifications"
        id: win
        screen: Focus.screen

        anchors {
            top: true
            bottom: true
            left: true
            right: true
        }

        exclusiveZone: 0
        color: "transparent"

        mask: Region { item: col }

        Column {
            id: col
            anchors.top: parent.top
            anchors.right: parent.right
            anchors.topMargin: 42
            anchors.rightMargin: 12
            spacing: 8

            // Cards below a dismissed one slide up rather than jumping.
            move: Transition {
                NumberAnimation {
                    properties: "y"
                    duration: 320
                    easing.type: Easing.OutBack
                    easing.overshoot: 0.9
                }
            }

            Repeater {
                model: server.trackedNotifications

                // NotificationCard declares `required property var modelData`,
                // so the Repeater injects the model row into it directly.
                NotificationCard {
                    // The card plays its leave animation first, then asks to go.
                    onClosed: modelData.dismiss()
                }
            }
        }
    }
}
