[general]
framerate = 60
autosens = 1
live-config = 1
bar_width = 6
bar_spacing = 1

[input]
method = pipewire
source = auto

[output]
method = noncurses

[color]
gradient = 1
gradient_color_1 = '{{colors.primary.default.hex}}'
gradient_color_2 = '{{colors.secondary.default.hex}}'
gradient_color_3 = '{{colors.tertiary.default.hex}}'

[smoothing]
noise_reduction = 77
