$wallpaper = {{image}}

$primary = rgb({{colors.primary.default.hex_stripped}})
$on_primary = rgb({{colors.on_primary.default.hex_stripped}})
$secondary = rgb({{colors.secondary.default.hex_stripped}})
$tertiary = rgb({{colors.tertiary.default.hex_stripped}})
$error = rgb({{colors.error.default.hex_stripped}})

$surface = rgba({{colors.surface.default.hex_stripped}}b3)
$surface_glass = rgba({{colors.surface_bright.default.hex_stripped}}26)
$on_surface = rgb({{colors.on_surface.default.hex_stripped}})
$on_surface_dim = rgba({{colors.on_surface_variant.default.hex_stripped}}cc)
$on_surface_faint = rgba({{colors.on_surface_variant.default.hex_stripped}}80)
$outline = rgba({{colors.outline.default.hex_stripped}}59)
$shadow = rgba(0000006e)

$placeholder = <span foreground="##{{colors.on_surface_variant.default.hex_stripped}}99">  password</span>
