$bg            = rgb({{colors.surface.default.hex_stripped}})
$bg_alt        = rgb({{colors.surface_variant.default.hex_stripped}})
$fg            = rgb({{colors.on_surface.default.hex_stripped}})
$fg_dim        = rgb({{colors.on_surface_variant.default.hex_stripped}})

$outline       = rgb({{colors.outline.default.hex_stripped}})
$outline_faint = rgb({{colors.outline_variant.default.hex_stripped}})

$accent        = rgb({{colors.primary.default.hex_stripped}})
$accent_alt    = rgb({{colors.tertiary.default.hex_stripped}})
$on_accent     = rgb({{colors.on_primary.default.hex_stripped}})

$error         = rgb({{colors.error.default.hex_stripped}})
$warn          = rgb({{colors.error.default.hex_stripped | set_hue: 45  | set_saturation: 75 | set_lightness: 70}})
$good          = rgb({{colors.error.default.hex_stripped | set_hue: 120 | set_saturation: 65 | set_lightness: 68}})

$active_border_1 = rgba({{colors.primary.default.hex_stripped}}ff)
$active_border_2 = rgba({{colors.tertiary.default.hex_stripped}}ff)
$inactive_border = rgba({{colors.outline.default.hex_stripped}}aa)

$shadow          = rgba({{colors.shadow.default.hex_stripped}}55)
$shadow_inactive = rgba({{colors.shadow.default.hex_stripped}}33)
