context.modules = [
  { name = libpipewire-module-echo-cancel
    args = {
      library.name = aec/libspa-aec-webrtc
      monitor.mode = true
      aec.args = {
        webrtc.noise_suppression = true
        webrtc.gain_control = true
        webrtc.high_pass_filter = true
        webrtc.voice_detection = true
        webrtc.extended_filter = false
        webrtc.delay_agnostic = true
      }
      capture.props = {
        node.name = "capture.pulse_elite_clean"
        target.object = "bluez_input.98:FA:2E:AD:E1:BE"
        node.passive = true
        node.dont-reconnect = false
      }
      source.props = {
        node.name = "pulse_elite_clean_mic"
        node.description = "PULSE Elite Mic (clean)"
      }
      sink.props = {
        node.name = "pulse_elite_aec_ref"
        node.passive = true
      }
    }
  }
]
