
context.modules = [
  { name = libpipewire-module-filter-chain
    args = {
      node.description = "Shell Equalizer"
      media.name       = "Shell Equalizer"
      filter.graph = {
        nodes = [
          { type = builtin name = eq_band_1  label = bq_lowshelf  control = { "Freq" = 32     "Q" = 1.0 "Gain" = 0.0 } }
          { type = builtin name = eq_band_2  label = bq_peaking   control = { "Freq" = 64     "Q" = 1.0 "Gain" = 0.0 } }
          { type = builtin name = eq_band_3  label = bq_peaking   control = { "Freq" = 125    "Q" = 1.0 "Gain" = 0.0 } }
          { type = builtin name = eq_band_4  label = bq_peaking   control = { "Freq" = 250    "Q" = 1.0 "Gain" = 0.0 } }
          { type = builtin name = eq_band_5  label = bq_peaking   control = { "Freq" = 500    "Q" = 1.0 "Gain" = 0.0 } }
          { type = builtin name = eq_band_6  label = bq_peaking   control = { "Freq" = 1000   "Q" = 1.0 "Gain" = 0.0 } }
          { type = builtin name = eq_band_7  label = bq_peaking   control = { "Freq" = 2000   "Q" = 1.0 "Gain" = 0.0 } }
          { type = builtin name = eq_band_8  label = bq_peaking   control = { "Freq" = 4000   "Q" = 1.0 "Gain" = 0.0 } }
          { type = builtin name = eq_band_9  label = bq_peaking   control = { "Freq" = 8000   "Q" = 1.0 "Gain" = 0.0 } }
          { type = builtin name = eq_band_10 label = bq_highshelf control = { "Freq" = 16000  "Q" = 1.0 "Gain" = 0.0 } }
        ]
        links = [
          { output = "eq_band_1:Out"  input = "eq_band_2:In" }
          { output = "eq_band_2:Out"  input = "eq_band_3:In" }
          { output = "eq_band_3:Out"  input = "eq_band_4:In" }
          { output = "eq_band_4:Out"  input = "eq_band_5:In" }
          { output = "eq_band_5:Out"  input = "eq_band_6:In" }
          { output = "eq_band_6:Out"  input = "eq_band_7:In" }
          { output = "eq_band_7:Out"  input = "eq_band_8:In" }
          { output = "eq_band_8:Out"  input = "eq_band_9:In" }
          { output = "eq_band_9:Out"  input = "eq_band_10:In" }
        ]
        inputs  = [ "eq_band_1:In" ]
        outputs = [ "eq_band_10:Out" ]
      }
      capture.props = {
        node.name   = "shell_eq_input"
        media.class = Audio/Sink
        audio.channels = 2
        audio.position = [ FL FR ]
      }
      playback.props = {
        node.name   = "shell_eq_output"
        node.passive = true
        audio.channels = 2
        audio.position = [ FL FR ]
      }
    }
  }
]
