general {
    hide_cursor = true
    fail_timeout = 1600
    ignore_empty_input = true
    text_trim = true
}

animations {
    enabled = false
}

background {
    monitor =
    color = rgb(000000)
    blur_passes = 0
}

label {
    monitor =
    text = $TIME
    color = rgb(f0f0f0)
    font_size = 96
    font_family = JetBrainsMono Nerd Font Thin
    position = 0, 180
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B"
    color = rgb(9a9a9a)
    font_size = 15
    font_family = JetBrainsMono Nerd Font
    position = 0, 108
    halign = center
    valign = center
}

label {
    monitor =
    text = $DESC
    color = rgb(707070)
    font_size = 12
    font_family = JetBrainsMono Nerd Font
    position = 0, -14
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 320, 46
    outline_thickness = 1
    dots_size = 0.24
    dots_spacing = 0.36
    dots_center = true
    dots_rounding = -1

    outer_color = rgb(3a3a3a)
    inner_color = rgb(000000)
    font_color = rgb(f0f0f0)
    check_color = rgb(f0f0f0)
    fail_color = rgb(c04040)

    fade_on_empty = false
    placeholder_text =
    fail_text = $FAIL
    rounding = 4

    position = 0, -70
    halign = center
    valign = center
}

label {
    monitor =
    text = $LAYOUT
    color = rgb(606060)
    font_size = 10
    font_family = JetBrainsMono Nerd Font
    position = 0, -128
    halign = center
    valign = center
}
