font=JetBrainsMono Nerd Font 10
background-color=#000000
text-color=#b0b0b0
border-color=#303030
progress-color=#303030

border-size=1
border-radius=0
padding=8
margin=0
width=320
height=120

anchor=top-right
layer=overlay
max-visible=3
default-timeout=5000
ignore-timeout=0
icons=0
markup=1
actions=1
history=1
max-history=20
sort=-time

[urgency=low]
text-color=#606060
default-timeout=3000

[urgency=critical]
text-color=#ffffff
border-color=#ff5555
default-timeout=0

[mode=dnd]
invisible=1
