[config]
reload_apps = true
set_wallpaper = false

[config.reload_apps_list]
kitty = true

[templates.kitty-colors]
input_path  = "~/.config/matugen/templates/kitty-colors.conf"
output_path = "~/.config/kitty/colors.conf"

[templates.cava]
input_path  = "~/.config/matugen/templates/cava.conf"
output_path = "~/.config/cava/config"

[templates.rofi]
input_path  = "~/.config/matugen/templates/rofi-colors.rasi"
output_path = "~/.config/rofi/colors/matugen.rasi"

[templates.hyprland]
input_path  = "~/.config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/hypr/config/colors.conf"
post_hook   = "hyprctl reload"

[templates.hyprlock]
input_path  = "~/.config/matugen/templates/hyprlock-colors.conf"
output_path = "~/.config/hypr/config/lock-colors.conf"

[templates.quickshell]
input_path  = "~/.config/matugen/templates/quickshell-colors.json"
output_path = "~/.cache/matugen/colors.json"

[templates.dunst]
input_path  = "~/.config/matugen/templates/dunstrc"
output_path = "~/.config/dunst/dunstrc"

[templates.wlogout]
input_path  = "~/.config/matugen/templates/wlogout-colors.css"
output_path = "~/.config/wlogout/colors.css"

[templates.gtk3]
input_path  = "~/.config/matugen/templates/gtk-colors.css"
output_path = "~/.config/gtk-3.0/gtk.css"
post_hook   = "python3 $HOME/.config/hypr/scripts/papirus-tint.py"

[templates.gtk4]
input_path  = "~/.config/matugen/templates/gtk-colors.css"
output_path = "~/.config/gtk-4.0/colors-matugen.css"

[templates.librewolf]
input_path  = "~/.config/matugen/templates/librewolf-userchrome.css"
output_path = "~/.config/matugen/out/librewolf-userchrome.css"
post_hook   = "python3 $HOME/.config/hypr/scripts/apply-browser-theme.py"

[templates.cursor]
input_path  = "~/.config/matugen/templates/cursor-trigger.txt"
output_path = "~/.config/matugen/out/cursor-trigger.txt"
post_hook   = "python3 $HOME/.config/hypr/scripts/gen-cursor-theme.py --reload"

[templates.rofi-list]
input_path  = "~/.config/matugen/templates/rofi-list.rasi"
output_path = "~/.config/rofi/themes/list.rasi"

[templates.rofi-grid]
input_path  = "~/.config/matugen/templates/rofi-grid.rasi"
output_path = "~/.config/rofi/themes/grid.rasi"
