exec-once = brightnessctl -c backlight set 70% 2>/dev/null
exec-once = hyprpolkitagent
exec-once = pipewire
exec-once = pipewire-pulse
exec-once = ~/.config/hypr/scripts/start-wireplumber.sh
exec-once = ~/.config/hypr/scripts/notify-trace.sh
exec-once = ~/.local/bin/shell-autostart
exec-once = ~/.config/hypr/scripts/fix-dbus.sh

exec-once = awww-daemon
exec-once = ~/.config/hypr/scripts/startup-wallpaper.sh
exec-once = ~/.config/hypr/scripts/wallpaper-rotate.sh
exec-once = xdg-user-dirs-update
exec-once = wl-paste --type text --watch ~/.config/hypr/scripts/cliphist-store.sh
exec-once = wl-paste --type image --watch cliphist -max-items 150 store
exec-once = wl-clip-persist --clipboard regular
exec-once = dbus-update-activation-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = ~/.config/hypr/scripts/mic-lock.sh

exec-once = hypridle

exec-once = ~/.config/hypr/scripts/downloads-sort.py

exec-once = hyprctl setcursor Matugen-Cursor 24
